import { RssConfig, SettingDialogConfig } from "./store.slint";

export global Logic {
    callback hide-window();

    callback new-rss(RssConfig);
    callback save-rss(string, RssConfig);
    callback delete-rss(string);
    callback switch-rss(string, string);
    callback toggle-rss-mark(int, string);
    callback sync-rss(string);

    callback set-rss-dialog(string);
    callback reset-rss-dialog();

    pure callback parse-tags(string) -> [string];
    parse-tags(tags) => { return [tags]; }

    callback favorite-entry(string, string);
    callback remove-entry(string, string);
    callback remove-all-entry(string);
    callback set-read-entry(string, string);
    callback set-read-all-entry(string);

    callback show-message(string, string);
    callback copy-to-clipboard(string);
    callback handle-ok-cancel-dialog(string, string);

    callback setting-cancel();
    callback setting-ok(SettingDialogConfig);
}

