import { RssConfig, RssEntry, SettingDialogConfig } from "./store.slint";

export global Logic {
    callback hide-window();

    callback new-rss(RssConfig);
    callback save-rss(string, RssConfig);
    callback delete-rss(string);
    callback switch-rss(string, string);
    callback toggle-rss-mark(int, string);
    callback sync-rss(string);

    callback set-rss-dialog(string);
    callback reset-rss-dialog();

    pure callback parse-tags(string) -> [string];
    parse-tags(tags) => { return [tags, "1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]; }

    pure callback unread-counts([RssEntry], int, bool) -> int;
    unread-counts(entrys, counts, flag) => { return entrys.length; }

    pure callback get-update-time(string, bool) -> string;
    get-update-time(suuid) => { return "2023-09-14 19:11"; }

    callback favorite-entry(string, string);
    callback remove-entry(string, string);
    callback remove-all-entry(string);
    callback set-read-entry(string, string);
    callback set-read-all-entry(string);
    callback open-url(string);
    callback toggle-unread-count-flag(string);

    callback clear-trash-box();

    callback show-message(string, string);
    callback copy-to-clipboard(string);
    callback handle-ok-cancel-dialog(string, string);

    callback setting-cancel();
    callback setting-ok(SettingDialogConfig);
}

