import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { IconBtn } from "../base/icon-btn.slint";
import { IconBtn } from "../base/icon-btn.slint";
import { Brand } from "../base/brand.slint";
import { CenterLayout } from "../base/center-layout.slint";
import { Tag } from "../base/tag.slint";

export component Body inherits Rectangle {
    private property<length> item-height: 45px;

    VerticalLayout {
        alignment: end;
        padding-bottom: Theme.padding * 4;
        CenterLayout {
            Brand {
                width: root.width * 0.5;
                opacity: 0.03;
            }
        }
    }

    Flickable {
        viewport-height: Store.rss-lists.length * root.item-height;

        for data[index] in Store.rss-lists : VerticalLayout {
            y: index * item-height;
            height: root.item-height;

            Rectangle {
                background: data.uuid == Store.current-rss-uuid ? Theme.base-background : (touch.has-hover ? Theme.darker-fill-color : Colors.transparent);

                touch := TouchArea {
                    mouse-cursor: self.has-hover ? pointer : default;
                    clicked => {
                        Logic.switch-rss(Store.current-rss-uuid, data.uuid);
                    }
                }

                HorizontalLayout {
                    padding-left: Theme.padding * 2;
                    padding-right: Theme.padding * 2;

                    if (data.uuid == Store.current-rss-uuid) : VerticalLayout {
                        alignment: center;
                        height: root.item-height;
                        padding-right: Theme.padding * 2;

                        Rectangle {
                            width: 4px;
                            height: 80%;
                            border-radius: 2px;
                            background: Theme.brand-color;
                        }
                    }

                    HorizontalLayout {
                        spacing: Theme.spacing * 2;

                        VerticalLayout {
                            alignment: center;
                            Image {
                                source: Store.icon-dialog-setting.icons[Math.max(0, Math.min(data.icon-index, Store.icon-dialog-setting.icons.length - 1))];
                                colorize: data.uuid == Store.current-rss-uuid ? Theme.brand-color : Theme.regular-text-color;
                                width: Theme.enlarge-font-size * 1.2;
                            }
                        }

                        name-txt := Text {
                            color: data.uuid == Store.current-rss-uuid ? Theme.brand-color : Theme.regular-text-color;
                            text: Store.rss-name(data.uuid, data.name);
                            font-size: Theme.enlarge-font-size;
                            overflow: elide;
                            vertical-alignment: center;
                        }
                    }

                    HorizontalLayout {
                        alignment: end;
                        spacing: Theme.spacing;
                        padding-left: Theme.padding;

                        VerticalLayout {
                            property<int> unread-counts: Logic.unread-counts(data.entry, data.entry.length, data.unread-counts-flag);

                            visible: unread-tag.text > 0;
                            alignment: center;
                            height: root.item-height;
                            unread-tag := Tag {
                                text: parent.unread-counts;
                                text-color: Theme.danger-color;
                                border-radius: self.height / 2;
                                h-padding: Theme.padding;
                                background: Colors.transparent;
                            }
                        }

                        start-vbox := VerticalLayout {
                            alignment: center;
                            IconBtn {
                                icon: @image-url("../images/star.svg");
                                colorize: data.is-mark ? Theme.mark-color : Theme.unmark-color;
                                clicked => {
                                    Logic.toggle-rss-mark(index, data.uuid);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
