import { CheckBox, ComboBox, LineEdit } from "std-widgets.slint";
import { CDialog } from "../../base/cdialog.slint";
import { Label } from "../../base/label.slint";
import { Store, RssConfig } from "../../store.slint";
import { Logic} from "../../logic.slint";
import { Theme} from "../../theme.slint";
import { IconBtn } from "../../base/icon-btn.slint";

export component RssDialog inherits CDialog {
    visible: Store.rss-dialog-setting.show;
    title: Store.rss-dialog-setting.handle-type == "rss-add" ? Store.translator.rss-dialog-title-new : Store.translator.rss-dialog-title-edit;

    width: 800px;

    property<length> text-width: Theme.default-label-width;
    in-out property<int> icon-index: 0;

    callback close();

    public function set(config: RssConfig) {
        line-edit-name.text = Store.rss-name(config.uuid, config.name);
        line-edit-url.text = config.url;
        use-proxy-checkbox.checked = config.use-proxy;
        root.icon-index = config.icon-index;

        feed-format-combobox.current-value = config.feed-format;
        if (config.feed-format == "") {
            feed-format-combobox.current-value = feed-format-combobox.model[0];
        }

        line-edit-name.enabled = !(config.uuid == "unread-uuid" || config.uuid == "favorite-uuid");
    }

    rect := Rectangle {
        background: Theme.base-background;
        VerticalLayout {
            padding: Theme.padding;
            spacing: Theme.spacing * 2;

            HorizontalLayout {
                txt-name := Label {
                    width: root.text-width;
                    text: Store.translator.rss-dialog-name;
                }

                line-edit-name := LineEdit {
                    placeholder-text: Store.translator.rss-dialog-name-placeholder;
                }

                VerticalLayout {
                    alignment: center;
                    padding-left: Theme.padding;
                    rss-icon := IconBtn {
                        icon: Store.icon-dialog-setting.icons[Math.max(0, Math.min(root.icon-index, Store.icon-dialog-setting.icons.length - 1))];
                        tip-pos: "left";
                        tip-text: Store.translator.tip-select-icon;
                        clicked => {
                            Store.icon-dialog-setting.show = true;
                        }
                    }
                }
            }

            HorizontalLayout {
                txt-url := Label {
                    width: root.text-width;
                    text: Store.translator.rss-dialog-url;
                }

                line-edit-url := LineEdit {
                    placeholder-text: Store.translator.rss-dialog-url-placeholder;
                    enabled: line-edit-name.enabled;
                }
            }

            HorizontalLayout {
                Label {
                    width: root.text-width;
                    text: Store.translator.rss-dialog-feed-format;
                }

                feed-format-combobox := ComboBox {
                    enabled: line-edit-name.enabled;
                    model: ["RSS", "ATOM"];
                    current-value: self.model[0];
                }
            }


            HorizontalLayout {
                HorizontalLayout {
                    use-proxy-checkbox := CheckBox {
                        text: self.checked ? Store.translator.rss-dialog-used-proxy : Store.translator.rss-dialog-unused-proxy;
                        enabled: line-edit-name.enabled;
                    }
                }
            }
        }
    }

    ok-clicked => {
        if (Store.rss-dialog-setting.handle-type == "rss-add") {
            Logic.new-rss({
                name: line-edit-name.text,
                url: line-edit-url.text,
                use-proxy: use-proxy-checkbox.checked,
                icon_index: root.icon-index,
                feed-format: feed-format-combobox.current-value,
            });
        } else if (Store.rss-dialog-setting.handle-type == "rss-edit") {
            Logic.save-rss(Store.current-rss-uuid, {
                name: line-edit-name.text,
                url: line-edit-url.text,
                use-proxy: use-proxy-checkbox.checked,
                icon_index: root.icon-index,
                feed-format: feed-format-combobox.current-value,
            });
        }

        Store.rss-dialog-setting.show = false;
        root.close();
    }

    cancel-clicked => {
        Store.rss-dialog-setting.show = false;
        root.close();
    }
}
