import { CheckBox, LineEdit, TextEdit } from "std-widgets.slint";
import { CDialog } from "../../base/cdialog.slint";
import { Label } from "../../base/label.slint";
import { Store, RssConfig } from "../../store.slint";
import { Logic} from "../../logic.slint";
import { Theme} from "../../theme.slint";
import { IconBtn } from "../../base/icon-btn.slint";

export component RssDialog inherits CDialog {
    visible: Store.rss-dialog-setting.show;
    title: Store.rss-dialog-setting.handle-type == "rss-add" ? Store.translator.rss-dialog-title-new : Store.translator.rss-dialog-title-edit;

    width: 600px;

    property<length> text-width: Theme.default-label-width;
    in-out property<int> icon-index: 0;

    callback close();

    public function set(config: RssConfig) {
        line-edit-name.text = config.name;
        use-proxy-checkbox.checked = config.use-proxy;
        root.icon-index = config.icon-index;
    }

    rect := Rectangle {
        background: Theme.base-background;
        VerticalLayout {
            padding: Theme.padding;
            spacing: Theme.spacing * 2;

            HorizontalLayout {
                txt-name := Label {
                    width: root.text-width;
                    text: Store.translator.rss-dialog-name;
                }

                line-edit-name := LineEdit {
                    placeholder-text: Store.translator.rss-dialog-name-placeholder;
                }

                VerticalLayout {
                    alignment: center;
                    padding-left: Theme.padding;
                    rss-icon := IconBtn {
                        icon: Store.icon-dialog-setting.icons[Math.max(0, Math.min(root.icon-index, Store.icon-dialog-setting.icons.length - 1))];
                        tip-pos: "left";
                        tip-text: Store.translator.tip-select-icon;
                        clicked => {
                            Store.icon-dialog-setting.show = true;
                        }
                    }
                }
            }

            HorizontalLayout {
                HorizontalLayout {
                    use-proxy-checkbox := CheckBox {
                        text: self.checked ? Store.translator.rss-dialog-used-proxy : Store.translator.rss-dialog-unused-proxy;
                    }
                }
            }
        }
    }

    ok-clicked => {
        if (Store.rss-dialog-setting.handle-type == "rss-add") {
            Logic.new-rss({
                name: line-edit-name.text,
                use-proxy: use-proxy-checkbox.checked,
                icon_index: root.icon-index,
            });
        } else if (Store.rss-dialog-setting.handle-type == "rss-edit") {
            Logic.save-rss(Store.current-rsslist-uuid, {
                name: line-edit-name.text,
                use-proxy: use-proxy-checkbox.checked,
                icon_index: root.icon-index,
            });
        }

        Store.rss-dialog-setting.show = false;
        root.close();
    }

    cancel-clicked => {
        Store.rss-dialog-setting.show = false;
        root.close();
    }
}
