import { Theme } from "../theme.slint";
import { Store } from "../store.slint";
import { Logic } from "../logic.slint";
import { IconBtn } from "../base/icon-btn.slint";
import { CenterLayout } from "../base/center-layout.slint";
import { Tip } from "../base/tip.slint";
import { Divider } from "../base/divider.slint";

export component Header inherits Rectangle {
    height: Theme.header-height;

    animate x {
        duration: Theme.default-animate-duration;
        easing: ease-in-out;
    }

    VerticalLayout {
        alignment: center;
        padding-left: Theme.padding * 2;
        padding-right: Theme.padding * 2;

        HorizontalLayout {
            spacing: Theme.spacing * 2;

            HorizontalLayout {
                alignment: start;
                spacing: Theme.spacing * 2;

                CenterLayout {
                    IconBtn {
                        icon: Theme.left-panel-width > 0 ?
                                  @image-url("../images/arrow-left.svg") :
                                  @image-url("../images/arrow-right.svg");

                        clicked => {
                            Theme.toggle-left-panel();
                        }
                    }
                }
            }

            HorizontalLayout {
                alignment: end;

                HorizontalLayout {
                    alignment: end;
                    spacing: Theme.spacing * 2;

                    IconBtn {
                        icon: @image-url("../images/reset.svg");
                        tip-pos: "left";
                        icon-width: self.width * 0.6;
                        tip-text: Store.translator.tip-sync-rss;
                        clicked => {
                            Logic.sync-rss();
                        }
                    }

                    IconBtn {
                        icon: @image-url("../images/mark-read.svg");
                        icon-width: self.width * 0.7;
                        tip-pos: "left";
                        tip-text: Store.translator.tip-set-all-read;
                        clicked => {
                            Logic.set-read-all-entry();
                        }
                    }

                    IconBtn {
                        icon: @image-url("../images/delete-light.svg");
                        tip-pos: "left";
                        tip-text: Store.translator.tip-delete-all;
                        clicked => {
                            Store.ok-cancel-dialog-setting.title-type = "warning";
                            Store.ok-cancel-dialog-setting.title-text = Store.translator.warning;
                            Store.ok-cancel-dialog-setting.body-text = Store.translator.delete-or-not;
                            Store.ok-cancel-dialog-setting.handle-type = "rss-all-entry";
                            Store.ok-cancel-dialog-setting.handle-uuid = Store.current-rss-uuid;
                        }
                    }
                }

                VerticalLayout {
                    alignment: center;
                    padding-left: Theme.padding * 2;
                    padding-right: Theme.padding * 2;

                    Divider {
                        width: 2px;
                        height: root.height * 0.5;
                        background: Theme.base-border-color;
                    }
                }

                HorizontalLayout {
                    spacing: Theme.spacing * 2;
                    IconBtn {
                        icon: @image-url("../images/setting-fill.svg");
                        tip-pos: "left";
                        tip-text: Store.translator.tip-setting;
                        clicked => {
                            Store.setting-dialog-config.show = true;
                        }
                    }

                    IconBtn {
                        icon: @image-url("../images/help.svg");
                        tip-pos: "left";
                        tip-text: Store.translator.tip-help;
                        clicked => {
                            Store.help-dialog.show = true;
                        }
                    }

                    IconBtn {
                        icon: @image-url("../images/info-dark.svg");
                        tip-pos: "left";
                        tip-text: Store.translator.tip-about;
                        clicked => {
                            Store.about-dialog.show = true;
                        }
                    }
                }
            }
        }
    }
}

