import { SpinBox, CheckBox, LineEdit } from "std-widgets.slint";
import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Label } from "../../base/label.slint";
import { Btn } from "../../base/btn.slint";
import { Logic } from "../../logic.slint";

export component RSS inherits VerticalLayout {
    in-out property sync-interval <=> sync-interval-spin-box.value;
    in-out property sync-interval-enabled <=> sync-interval-checkbox.checked;
    in-out property sync-timeout <=> sync-timeout-spin-box.value;
    in-out property browser <=> browser-lineedit.text;
    in-out property start-sync <=> start-sync-checkbox.checked;

    VerticalLayout {
        spacing: Theme.spacing * 4;
        alignment: start;

        HorizontalLayout {
            Label {
                width: Theme.default-label-width;
                text: Store.translator.setting-dialog-rss-sync-interval;
            }

            sync-interval-spin-box := SpinBox {
                enabled: true;
                minimum: 0;
                maximum: 12*60;
            }
        }

        HorizontalLayout {
            Label {
                width: Theme.default-label-width;
                text: Store.translator.setting-dialog-rss-sync-timeout;
            }

            sync-timeout-spin-box := SpinBox {
                enabled: true;
                minimum: 10;
                maximum: 60;
            }
        }

        HorizontalLayout {
            Label {
                width: Theme.default-label-width;
                text: Store.translator.setting-dialog-rss-sync-browser;
            }

            browser-lineedit := LineEdit {
                placeholder-text: Store.translator.setting-dialog-rss-sync-browser-placeholder;
            }
        }

        HorizontalLayout {
            sync-interval-checkbox := CheckBox {
                text: self.checked ? Store.translator.setting-dialog-rss-enabled-sync-interval : Store.translator.setting-dialog-rss-disabled-sync-interval;
            }

            start-sync-checkbox := CheckBox {
                text: self.checked ? Store.translator.setting-dialog-rss-start-sync-enabled : Store.translator.setting-dialog-rss-start-sync-disabled;
            }
        }

        HorizontalLayout {
            Btn {
                bg-color: Theme.danger-color;
                text: Store.translator.setting-dialog-rss-clear-trash + " (" + Store.setting-dialog-config.rss.trash-count + ")";
                icon: @image-url("../../images/warning.svg");
                clicked => {
                    Logic.clear-trash-box();
                }

            }
        }
    }
}
