import { Theme } from "../../theme.slint";
import { Store } from "../../store.slint";
import { Logic } from "../../logic.slint";
import { CenterLayout } from "../../base/center-layout.slint";
import { IconBtn } from "../../base/icon-btn.slint";
import { Tag } from "../../base/tag.slint";
import { Tip } from "../../base/tip.slint";

export component ToolBar inherits Rectangle {
    in-out property<bool> is-read: false;
    in-out property<string> uuid;
    in-out property<string> suuid;
    in-out property<string> url;

    in-out property<bool> is-up-summary: false;

    HorizontalLayout {
        padding-bottom: Theme.padding;
        alignment: end;

        HorizontalLayout {
            padding-right: Theme.padding;
            spacing: Theme.spacing * 2;

            CenterLayout {
                IconBtn {
                icon: root.is-up-summary ? @image-url("../../images/arrow-up.svg") : @image-url("../../images/arrow-down.svg");
                    tip-text: Store.translator.tip-down-summary;
                    tip-pos: "left";
                    clicked => {
                        root.is-up-summary = !root.is-up-summary;
                    }
                }
            }

            CenterLayout {
                IconBtn {
                    icon: @image-url("../../images/star-light.svg");
                    tip-text: Store.translator.tip-favorite;
                    tip-pos: "left";
                    clicked => {
                        Logic.favorite-entry(Store.current-rss-uuid, root.uuid);
                    }
                }
            }

            CenterLayout {
                IconBtn {
                    icon: @image-url("../../images/copy.svg");
                    icon-width: self.width * 0.7;
                    tip-text: Store.translator.tip-copy-url;
                    tip-pos: "left";
                    clicked => {
                        Logic.copy-to-clipboard(root.url);
                    }
                }
            }

            CenterLayout {
                IconBtn {
                    icon: @image-url("../../images/mark-read.svg");
                    icon-width: self.width * 0.7;
                    tip-text: Store.translator.tip-mark-read;
                    tip-pos: "left";
                    clicked => {
                        Logic.set-read-entry(Store.current-rss-uuid, root.uuid);
                        debug(root.suuid, root.uuid);
                        Logic.toggle-unread-count-flag("unread-uuid");
                        if (Store.current-rss-uuid == "unread-uuid") {
                            Logic.toggle-unread-count-flag(root.suuid);
                        } else {
                            Logic.toggle-unread-count-flag(Store.current-rss-uuid);
                        }
                    }
                }
            }

            CenterLayout {
                IconBtn {
                    icon: @image-url("../../images/delete-light.svg");
                    tip-text: Store.translator.tip-delete;
                    tip-pos: "left";
                    clicked => {
                        Store.ok-cancel-dialog-setting.title-type = "warning";
                        Store.ok-cancel-dialog-setting.title-text = Store.translator.warning;
                        Store.ok-cancel-dialog-setting.body-text = Store.translator.delete-or-not;
                        Store.ok-cancel-dialog-setting.handle-type = "rss-entry";
                        Store.ok-cancel-dialog-setting.handle-uuid = root.uuid;
                    }
                }
            }

        }
    }
}
